"""Validates each marketing use case against the live Trove API.

For each use case it:
  1. Stages real input files (uploads from local OR generates in-container).
  2. Runs the exact shell command we want to advertise.
  3. Prints command + verbatim output, ready to paste into marketing copy.

Test fixtures used:
  - contract.pdf : multi-line synthetic PDF with searchable contract clauses
  - photo.jpg    : 800x600 JPEG with GPS + camera EXIF, generated by ImageMagick
  - clip.mp3     : 3s 440Hz tone, generated by ffmpeg lavfi
  - sales.csv    : 6-row sales spreadsheet
  - users.json   : list of users with `churned` flag
"""
from __future__ import annotations

import os
import struct
import zlib
from pathlib import Path
from textwrap import dedent

from trove_sdk import TroveClient


def load_env(path: Path) -> dict[str, str]:
    env: dict[str, str] = {}
    for line in path.read_text().splitlines():
        line = line.strip()
        if line and "=" in line and not line.startswith("#"):
            k, _, v = line.partition("=")
            env[k.strip()] = v.strip()
    return env


# ── Build a richer synthetic PDF with multi-line text (so pdftotext + grep work) ──

def rich_pdf() -> bytes:
    """Single-page PDF with several lines of contract-style text."""
    text_lines = [
        "ACME Corporation Master Service Agreement",
        "",
        "Section 1: Termination Clauses",
        "Either party may terminate this Agreement upon thirty days written notice.",
        "In the event of a material breach, immediate termination is permitted.",
        "Termination shall not affect any accrued rights or obligations.",
        "",
        "Section 2: Confidentiality",
        "All Confidential Information shall remain protected for ten years.",
        "",
        "Section 3: Limitation of Liability",
        "Neither party shall be liable for indirect or consequential damages.",
    ]

    # Build the content stream — one Tj per line, manual leading.
    parts = ["BT", "/F1 11 Tf", "72 720 Td", "13 TL"]
    for i, line in enumerate(text_lines):
        if i > 0:
            parts.append("T*")
        # PDF strings: parens are special, escape them
        safe = line.replace("(", r"\(").replace(")", r"\)")
        parts.append(f"({safe}) Tj")
    parts.append("ET")
    stream = "\n".join(parts).encode("latin-1")

    # Assemble PDF
    objs = [
        b"<</Type/Catalog/Pages 2 0 R>>",
        b"<</Type/Pages/Kids [3 0 R]/Count 1>>",
        b"<</Type/Page/Parent 2 0 R/MediaBox [0 0 612 792]/Resources <</Font <</F1 4 0 R>>>>/Contents 5 0 R>>",
        b"<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>",
        b"<</Length " + str(len(stream)).encode() + b">>stream\n" + stream + b"\nendstream",
    ]
    out = bytearray(b"%PDF-1.4\n%\xc7\xec\x8f\xa2\n")
    offsets = [0]
    for i, obj in enumerate(objs, start=1):
        offsets.append(len(out))
        out += f"{i} 0 obj ".encode() + obj + b" endobj\n"
    xref_pos = len(out)
    out += b"xref\n0 " + str(len(objs) + 1).encode() + b"\n"
    out += b"0000000000 65535 f \n"
    for off in offsets[1:]:
        out += f"{off:010d} 00000 n \n".encode()
    out += b"trailer <</Size " + str(len(objs) + 1).encode() + b"/Root 1 0 R>>\nstartxref\n"
    out += str(xref_pos).encode() + b"\n%%EOF\n"
    return bytes(out)


# ── Section runner ────────────────────────────────────────────────────────────

def section(title: str) -> None:
    print(f"\n{'═' * 60}\n  {title}\n{'═' * 60}")

def run(client: TroveClient, command: str) -> str:
    """Run one shell command, print it, return stdout for downstream checks."""
    print(f"\n$ {command}")
    out = client.exec(command)
    print(out.rstrip() if out else "(no output)")
    return out


def main() -> int:
    env = load_env(Path(__file__).resolve().parents[2] / ".env")
    api_key = env["TROVE_API_KEY"]
    namespace = "usecases"

    with TroveClient(api_key=api_key, namespace=namespace) as client:
        # ── Stage fixtures ────────────────────────────────────────────────
        client.upload("workspace/contract.pdf", rich_pdf())
        client.write("workspace/sales.csv", dedent("""\
            customer,amount,region
            Acme,12500,us-east
            Globex,3200,us-west
            Initech,18900,eu
            Umbrella,5600,us-east
            Hooli,22100,apac
            Pied Piper,890,us-west
        """))
        client.write("workspace/users.json", dedent("""\
            {
              "users": [
                {"id": 1, "name": "alice", "churned": false, "plan": "pro"},
                {"id": 2, "name": "bob",   "churned": true,  "plan": "free"},
                {"id": 3, "name": "carol", "churned": true,  "plan": "pro"},
                {"id": 4, "name": "dave",  "churned": false, "plan": "team"}
              ]
            }
        """))
        # Generate audio + JPEG with EXIF using the container itself
        client.exec("ffmpeg -y -f lavfi -i sine=frequency=440:duration=3 -ar 44100 "
                    "workspace/clip.mp3 2>/dev/null && echo done")
        client.exec("convert -size 800x600 xc:lightblue workspace/photo.jpg && "
                    "exiftool -overwrite_original -q -GPSLatitude=40.7128 -GPSLongitude=-74.0060 "
                    "-GPSLatitudeRef=N -GPSLongitudeRef=W -Make=Apple -Model='iPhone 14' "
                    "workspace/photo.jpg && echo done")

        # ── Use case 1: PDF RAG ───────────────────────────────────────────
        section("Use Case 1 — PDF RAG without a data loader")
        run(client, "pdfinfo workspace/contract.pdf | head -8")
        run(client, "pdftotext workspace/contract.pdf - | head -5")
        run(client, "pdftotext workspace/contract.pdf - | grep -B 1 -A 2 -i termination")

        # ── Use case 2: Vision preprocessing ──────────────────────────────
        section("Use Case 2 — Vision preprocessing for cheaper inference")
        run(client, "identify workspace/photo.jpg")
        run(client, "exiftool -GPSLatitude -GPSLongitude -Make -Model workspace/photo.jpg")
        run(client, "convert workspace/photo.jpg -resize 256x256 -strip workspace/thumb.jpg && "
                    "identify workspace/thumb.jpg && "
                    "exiftool -GPSLatitude workspace/thumb.jpg")

        # ── Use case 3: Audio transcription prep ──────────────────────────
        section("Use Case 3 — Audio prep for Whisper-ready input")
        run(client, "ffprobe -v quiet -print_format json -show_format workspace/clip.mp3 | "
                    "jq '{duration: .format.duration, bitrate: .format.bit_rate}'")
        run(client, "ffmpeg -y -i workspace/clip.mp3 -ar 16000 -ac 1 workspace/whisper.wav 2>/dev/null && "
                    "ffprobe -v quiet -print_format json -show_streams workspace/whisper.wav | "
                    "jq '.streams[0] | {sample_rate, channels, codec_name}'")

        # ── Use case 4: CSV / JSON data sandbox ───────────────────────────
        section("Use Case 4 — Per-customer data sandbox")
        run(client, "awk -F, 'NR>1 && $2>10000 {print $1, \"-\", $2}' workspace/sales.csv")
        run(client, "awk -F, 'NR>1 {sum[$3]+=$2} END {for (r in sum) print r, sum[r]}' workspace/sales.csv | sort -k2 -rn")
        run(client, "jq '.users[] | select(.churned) | {name, plan}' workspace/users.json")

        # ── Use case 5: Hashing / integrity (light bonus) ─────────────────
        section("Use Case 5 — Verifying customer-uploaded artifacts")
        run(client, "file workspace/contract.pdf workspace/photo.jpg workspace/clip.mp3")
        run(client, "sha256sum workspace/contract.pdf workspace/photo.jpg")

        # ── Cleanup ───────────────────────────────────────────────────────
        client.exec("rm -rf workspace/*")

    print("\n" + "═" * 60)
    print("  DONE — all commands above executed against live API")
    print("═" * 60)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
